# Generated by Django 5.0.6 on 2024-05-19 14:54

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('NOTE', 'NOTE'), ('REMINDER', 'REMINDER'), ('PIC', 'PIC')])),
                ('data', models.JSONField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'memories',
            },
        ),
        migrations.CreateModel(
            name='Neuron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', pgvector.django.VectorField(dimensions=1536)),
            ],
            options={
                'db_table': 'neurons',
            },
        ),
        migrations.CreateModel(
            name='MemorySyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_id', models.CharField(max_length=100)),
                ('biz_modified_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'memories_sync_log',
                'ordering': ['-biz_modified_at'],
                'indexes': [models.Index(fields=['biz_modified_at'], name='idx_biz_modified_at')],
            },
        ),
        migrations.AddConstraint(
            model_name='memorysynclog',
            constraint=models.UniqueConstraint(fields=('biz_id',), name='uk_biz_id'),
        ),
        migrations.AddIndex(
            model_name='neuron',
            index=pgvector.django.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_hnsw_embedding', opclasses=['vector_cosine_ops']),
        ),
    ]
